# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct LabelsApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_apiV1FleetLabelsGet(_api::LabelsApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Any, "/api/v1/fleet/labels", ["bearerAuth"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Labels

Params:

Return: Any
"""
function apiV1FleetLabelsGet(_api::LabelsApi; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLabelsGet(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function apiV1FleetLabelsGet(_api::LabelsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLabelsGet(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

function _swaggerinternal_apiV1FleetLabelsLabelIdGet(_api::LabelsApi, label_id::String; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Any, "/api/v1/fleet/labels/{label_id}", ["bearerAuth"])
    Swagger.set_param(_ctx.path, "label_id", label_id)  # type String
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Label by ID

Params:
- label_id::String (required)

Return: Any
"""
function apiV1FleetLabelsLabelIdGet(_api::LabelsApi, label_id::String; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLabelsLabelIdGet(_api, label_id; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function apiV1FleetLabelsLabelIdGet(_api::LabelsApi, response_stream::Channel, label_id::String; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLabelsLabelIdGet(_api, label_id; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export apiV1FleetLabelsGet, apiV1FleetLabelsLabelIdGet
