# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct GeneralApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_apiV1FleetLoginPost(_api::GeneralApi; body=nothing, _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "POST", Any, "/api/v1/fleet/login", [], body)
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json"] : [_mediaType])
    return _ctx
end

@doc raw"""Login

Params:
- body::Any

Return: Any
"""
function apiV1FleetLoginPost(_api::GeneralApi; body=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLoginPost(_api; body=body, _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function apiV1FleetLoginPost(_api::GeneralApi, response_stream::Channel; body=nothing, _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetLoginPost(_api; body=body, _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export apiV1FleetLoginPost
