# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

struct SoftwareApi <: SwaggerApi
    client::Swagger.Client
end

function _swaggerinternal_apiV1FleetSoftwareGet(_api::SoftwareApi; _mediaType=nothing)
    _ctx = Swagger.Ctx(_api.client, "GET", Nothing, "/api/v1/fleet/software", ["bearerAuth"])
    Swagger.set_header_accept(_ctx, ["application/json"])
    Swagger.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Software

Params:

Return: Nothing
"""
function apiV1FleetSoftwareGet(_api::SoftwareApi; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetSoftwareGet(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx)
end

function apiV1FleetSoftwareGet(_api::SoftwareApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _swaggerinternal_apiV1FleetSoftwareGet(_api; _mediaType=_mediaType)
    Swagger.exec(_ctx, response_stream)
end

export apiV1FleetSoftwareGet
