# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module Fleetdm

using Random
using Dates
using Swagger
import Swagger: field_name, property_type, hasproperty, validate_property, SwaggerApi, SwaggerModel
import Base: convert, propertynames

include("modelincludes.jl")

include("api_GeneralApi.jl")
include("api_HostsApi.jl")
include("api_LabelsApi.jl")
include("api_SoftwareApi.jl")
include("api_UsersApi.jl")

# export models

# export operations
export convert, GeneralApi, HostsApi, LabelsApi, SoftwareApi, UsersApi

export check_required, field_name, property_type, hasproperty, propertynames, validate_property, convert

end
