# This file was originally generated by the Julia Swagger Code Generator
# It has since been manually modified, and added to .swagger-codegen-ignore
# Fixup needed here when a new Api is created in the spec. 

module Fleetdm

using Random
using Dates
using Swagger
import Swagger: field_name, property_type, hasproperty, validate_property, SwaggerApi, SwaggerModel
import Base: convert, propertynames

include("modelincludes.jl")

include("api_GeneralApi.jl")
include("api_HostsApi.jl")
include("api_LabelsApi.jl")
include("api_SoftwareApi.jl")
include("api_UsersApi.jl")

# export models

# export operations
export convert, GeneralApi, HostsApi, LabelsApi, SoftwareApi, UsersApi

export check_required, field_name, property_type, hasproperty, propertynames, validate_property, convert

end
